/**
 * @file Automatically generated by barrelsby.
 */

import * as ennamesfirstNamesfemalets from "./en/names/firstNames/female";
import * as ennamesfirstNamesmalets from "./en/names/firstNames/male";
export const en = {
  names: {
    firstNames: {
      female: ennamesfirstNamesfemalets,
      male: ennamesfirstNamesmalets,
    },
  },
};
